Question1: Cancer Diagnosis Using Machine Learning

In [30]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier

#importing the database over
df  = pd.read_csv("https://github.com/mpourhoma/CS4661/raw/master/Cancer.csv")

df[0:5]
#Great it loaded :DD

,Clump_Thickness,Uniformity_of_Cell_Size,Uniformity_of_Cell_Shape,Marginal_Adhesion,Single_Epithelial_Cell_Size,Bare_Nuclei,Bland_Chromatin,Normal_Nucleoli,Mitoses,Malignant_Cancer
0,5,1,1,1,2,1,3,1,1,0
1,5,4,4,5,7,10,3,2,1,0
2,3,1,1,1,2,2,3,1,1,0
3,6,8,8,1,3,4,3,7,1,0
4,4,1,1,3,2,1,3,1,1,0


In [31]:
#Great with it loading we check other variables needed :DD

df.columns

Index(['Clump_Thickness', 'Uniformity_of_Cell_Size',
       'Uniformity_of_Cell_Shape', 'Marginal_Adhesion',
       'Single_Epithelial_Cell_Size', 'Bare_Nuclei', 'Bland_Chromatin',
       'Normal_Nucleoli', 'Mitoses', 'Malignant_Cancer'],
      dtype='object')

In [32]:
X = df[['Clump_Thickness', 'Uniformity_of_Cell_Size',
       'Uniformity_of_Cell_Shape', 'Marginal_Adhesion',
       'Single_Epithelial_Cell_Size', 'Bare_Nuclei', 'Bland_Chromatin',
       'Normal_Nucleoli', 'Mitoses']]
y = df['Malignant_Cancer']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.35, random_state=3)

#This is just to see how it's split :))
print(X_train.shape)
print(X_test.shape)

(97, 9)
(53, 9)


In [33]:
myDT = DecisionTreeClassifier(random_state=3)

myDT.fit(X_train,y_train)
yPred = myDT.predict(X_test)

acc = accuracy_score(y_test, yPred)

print(acc)

0.8301886792452831


In [34]:
pred = []

for i in range(50):
    X_boot, y_boot = resample(X_train, y_train, n_samples=int(0.8 * len(X_train)), random_state=i, replace=True)

    BDT = DecisionTreeClassifier(random_state=3)
    BDT.fit(X_boot, y_boot)

    preds = BDT.predict(X_test)

    pred.append(preds)

#Else it's gonna look CRAZY!!!
pred = np.array(pred)
print(pred)

[[1 1 1 ... 0 1 1]
 [1 1 1 ... 0 1 1]
 [1 1 0 ... 0 1 1]
 ...
 [0 1 0 ... 0 1 1]
 [0 1 0 ... 0 1 1]
 [1 1 0 ... 1 1 1]]
